name: Deploy Logicapp App

on:
  push:
    branches:
      - main
    paths:
      - 'LogicAppWorkflow/*'

  workflow_dispatch:

env:
  LOGICAPP_PACKAGE_PATH: './LogicAppWorkflow' 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Logic App'
      uses: azure/functions-action@v1
      with:
        app-name: 'lapp4-rhym-poc-eus2'
        package: ${{ env.LOGICAPP_PACKAGE_PATH }}
